@startuml CU-11_administrar_catalogos_servicios
!theme plain
skinparam backgroundColor #FFFFFF
skinparam roundcorner 8
skinparam defaultFontName Arial
skinparam defaultFontSize 11
skinparam packageBackgroundColor #F8FAFC
skinparam packageBorderColor #64748B
left to right direction

title Caso de Uso Específico: CU-11: Administrar Catálogos, Cargos y Delegaciones\nSistema SGR - Municipalidad de La Serena

actor "Administrador Central" as ACT_PRIMARY #e0f2fe
actor "Módulo de Datos Maestros" as ACT_SYS #f1f5f9

rectangle "Sistema de Gestión de Resultados (SGR)" {
    usecase "Administrar Catálogos Municipales" as UC_BASE #dbeafe
    usecase "Registrar o Editar Servicio" as INC_1 #f8fafc
    usecase "Asociar Servicio a Cargo Territorial" as INC_2 #f8fafc
    usecase "Notificar Servicio con Procesos Activos" as EXT_1 #fff1f2

    ' Relaciones de Inclusión
    UC_BASE ..> INC_1 : <<include>>
    UC_BASE ..> INC_2 : <<include>>

    ' Relaciones de Extensión
    EXT_1 ..> UC_BASE : <<extend>>\n(Condición: Se intenta borrar ítem con evidencias)
}

ACT_PRIMARY --> UC_BASE
UC_BASE --> ACT_SYS

@enduml